- name: Build a text based ST Mint distribution using the bash shell
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - import_tasks: basemint_tasks.yml

    - name: disable xaaes startup
      replace:
        path: build/mint/{{ version }}/mint.cnf
        regexp : '^GEM=u:/c/mint/{{ version }}/xaaes/xaloader.prg$'
        replace: '#GEM=u:/c/mint/{{ version }}/xaaes/xaloader.prg'
    
    - name: start mksh shell after boot
      replace:
        path: build/mint/{{ version }}/mint.cnf
        regexp: '^#INIT=u:/c/mint/init.prg$'
        replace: 'INIT=u:/bin/mksh'
