- name: Build a ST Mint distribution using the TOS AES
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - minor_version: 2a8
    - major_version: 1-19
    - version: "{{ major_version }}-{{ minor_version }}"
  tasks:
    - import_tasks: basemint.yml

    - name: use the ROM AES
      replace:
        path: "build/mint/{{ version }}/mint.cnf"
        regexp: '^#GEM=ROM$'
        replace: 'GEM=ROM'

    - name: copy nohog.acc to fix keyboard input
      copy:
        src: "build/mint/{{ version }}/sys-root/opt/GEM/nohog2/nohog2.acc"
        dest: build

