- name: Build a ST Mint distribution using Xaaes
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - minor_version: 2a8
    - major_version: 1-19
    - version: "{{ major_version }}-{{ minor_version }}"
  tasks:
    - import_tasks: basemint.yml
    - import_tasks: xaaes.yml
